version: '3.1'

services:
  
  springboot:
    image: ramurams/springapp:1
    container_name: springboot
    ports:
      - 8080:8080
    environment:
      - MONGO_DB_HOSTNAME=mongo
      - MONGO_DB_USERNAME=devdb
      - MONGO_DB_PASSWORD=devdb1234
    depends_on:
      - mongo
    deploy:
      replicas: 2
  mongo:
    image: mongo
    container_name: mongo-springboot
    networks:
      - overlaydemo
    environment:
      - MONGODB_INIT_ROOT_USERNAME=devdb
      - MONGODB_INIT_ROOT_PASSWORD=devdb@123
networks:
  overlaydemo:
    external: true
