apiVersion: apps/v1
kind: Deployment
metadata:
  name: Springbootd
  namespace: test-ns
spec:
  selector:
    matchLabels:
      app: springapp
  template:
    metadata:
      name: springd-pod
      labels:
        app: springapp
    spec:
      containers:
        - name: springd-con
          image: ramurams/spring-app:1
          ports:
            - containerPort: 8080
          env: 
          - name: MONGO_DB_HOSTNAME
            value:  mongosvc
          - name: MONGO_DB_USERNAME
            value: devdb
          - name: MONGO_DB_PASSWORD
            value: devdb@123 
  
---

apiVersion: v1 
kind: Service
metadata:
  name: springapp-svc
  namespace: test-ns
spec:
  type: NodePort
  selector:
    app: springapp
  ports:
  - port: 80
    targetPort: 8080

---

apiVersion: apps/v1 
kind: Deployment
metadata:
  name: mongodb
  namespace: test-ns
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      name: mongo-pod
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongo-con
          image: mongo
          ports:
            - containerPort: 27017
          env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: devdb
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: devdb@123

---

apiVersion: v1 
kind: Service
metadata:
  name: mongosvc
  namespace: test-ns
spec:
  type: ClusterIP
  selector:
    app: mongodb
  ports:
  - port: 80
    targetPort: 27017

